spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver


  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000
      client-type: lettuce

  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
